<a href="https://colab.research.google.com/github/olgaklimova/Experimental-Studies/blob/main/ExperimentalStudies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import pandas as pd
import numpy as np

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/ExperimentalStudies/train_st_till_june.csv')

In [60]:
df2 = pd.read_csv('/content/drive/MyDrive/ExperimentalStudies/train_w_areas_st_till_june.csv')

In [ ]:
from IPython.display import display
display(df1)

In [61]:
display(df2)

,Unnamed: 0,UID,GID,Area,JobName,Partition,ReqNodes,ReqCPUS,Timelimit,Submit,Start,Elapsed,Priority,State,ExitCode
0,0,1420,88068,astrophys,Smilei0,tornado,70,1960,10-00:00:00,2021-08-11T16:53:04,2021-09-17T09:46:21,1-11:27:29,1,CANCELLED by 50260,0:0
1,1,52951,3414,phys,v149_td,tornado,2,56,14-00:00:00,2021-08-18T10:38:10,2021-08-18T10:46:12,14-00:00:38,1,TIMEOUT,0:0
2,2,24801,97723,mech,fluent,tornado,6,168,14-00:00:00,2021-08-18T14:50:05,2021-08-18T14:50:05,13-21:05:40,1,CANCELLED by 50341,0:0
3,3,24801,97723,mech,fluent,tornado,6,168,14-00:00:00,2021-08-18T14:52:31,2021-08-18T14:52:32,13-21:04:39,1,CANCELLED by 50341,0:0
4,4,70802,33028,energ,dcss.slurm,tornado-k40,1,1,14-00:00:00,2021-08-19T15:33:49,2021-08-19T15:33:50,14-00:00:04,1,TIMEOUT,0:0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1290724,1290724,70637,47128,mech,lsdyna,tornado,1,28,10-00:00:00,2023-05-31T23:42:30,2023-05-31T23:42:30,05:19:37,480,COMPLETED,0:0
1290725,1290725,70637,47128,mech,lsdyna,tornado,1,28,10-00:00:00,2023-05-31T23:42:47,2023-05-31T23:42:47,05:25:22,480,COMPLETED,0:0
1290726,1290726,70637,47128,mech,lsdyna,tornado,1,28,10-00:00:00,2023-05-31T23:43:10,2023-05-31T23:43:12,05:28:30,480,COMPLETED,0:0
1290727,1290727,72271,99243,phys,mymatlabjob,tornado,1,1,1-00:00:00,2023-05-31T23:51:20,2023-05-31T23:51:20,00:01:06,233,COMPLETED,0:0
1290728,1290728,72271,99243,phys,mymatlabjob,tornado,1,1,1-00:00:00,2023-05-31T23:54:14,2023-05-31T23:54:14,05:01:54,233,COMPLETED,0:0

In [ ]:
data = df2
num_rows = data.shape[0]
#удаление строки данных с неполной информацией
data = data.drop(303747)
#удаление колонки с индексами строк
first_column_name = data.columns[0]
data = data.drop(columns=[first_column_name])
display(data)

In [ ]:
#Преобразование категориальных признаков

#One-Hot Encoding
#признак "Area"
one_hot_encoding_1_data = pd.get_dummies(data['Area'])
#добавление новых колонок к исходному датафрейму
data = pd.concat([data, one_hot_encoding_1_data], axis=1)
data = data.drop(columns=['Area'])

#признак "Partition"
one_hot_encoding_2_data = pd.get_dummies(data['Partition'])
#добавление новых колонок к исходному датафрейму
data = pd.concat([data, one_hot_encoding_2_data], axis=1)
data = data.drop(columns=['Partition'])

##признак "State"
#one_hot_encoding_3_data = pd.get_dummies(data['State'])
##добавление новых колонок к исходному датафрейму
#data = pd.concat([data, one_hot_encoding_3_data], axis=1)
#data = data.drop(columns=['State'])

display(data)

In [36]:
!pip install category_encoders
import category_encoders as ce

Requirement already satisfied: category_encoders in /usr/local/lib/python3.10/dist-packages (2.6.3)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.25.2)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.11.4)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.14.1)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.5.3)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.5.6)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2023.4)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.3.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (24.0)

In [ ]:
print(data['ExitCode'].unique())

In [64]:
#Преобразование форматов столцов Elapsed_Seconds и Timelimit_Seconds
def parse_time(time_str):
    if '-' in time_str:
        days, time = time_str.split('-')
    else:
        days = '0'
        time = time_str
    hours, minutes, seconds = map(int, time.split(':'))
    result = int(days)*86400 + hours*3600 + minutes*60 + seconds
    return result

# Применение функции к каждой строке столбца
data['Elapsed_Seconds'] = data['Elapsed'].apply(parse_time)
data = data.drop(columns=['Elapsed'])

data['Timelimit_Seconds'] = data['Timelimit'].apply(parse_time)
data = data.drop(columns=['Timelimit'])

display(data)

,UID,GID,JobName,ReqNodes,ReqCPUS,Submit,Start,Priority,State,ExitCode,...,mech,phys,radiophys,cascade,g2,nv,tornado,tornado-k40,Elapsed_Seconds,Timelimit_Seconds
0,1420,88068,Smilei0,70,1960,2021-08-11T16:53:04,2021-09-17T09:46:21,1,CANCELLED by 50260,0:0,...,0,0,0,0,0,0,1,0,127649,864000
1,52951,3414,v149_td,2,56,2021-08-18T10:38:10,2021-08-18T10:46:12,1,TIMEOUT,0:0,...,0,1,0,0,0,0,1,0,1209638,1209600
2,24801,97723,fluent,6,168,2021-08-18T14:50:05,2021-08-18T14:50:05,1,CANCELLED by 50341,0:0,...,1,0,0,0,0,0,1,0,1199140,1209600
3,24801,97723,fluent,6,168,2021-08-18T14:52:31,2021-08-18T14:52:32,1,CANCELLED by 50341,0:0,...,1,0,0,0,0,0,1,0,1199079,1209600
4,70802,33028,dcss.slurm,1,1,2021-08-19T15:33:49,2021-08-19T15:33:50,1,TIMEOUT,0:0,...,0,0,0,0,0,0,0,1,1209604,1209600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1290724,70637,47128,lsdyna,1,28,2023-05-31T23:42:30,2023-05-31T23:42:30,480,COMPLETED,0:0,...,1,0,0,0,0,0,1,0,19177,864000
1290725,70637,47128,lsdyna,1,28,2023-05-31T23:42:47,2023-05-31T23:42:47,480,COMPLETED,0:0,...,1,0,0,0,0,0,1,0,19522,864000
1290726,70637,47128,lsdyna,1,28,2023-05-31T23:43:10,2023-05-31T23:43:12,480,COMPLETED,0:0,...,1,0,0,0,0,0,1,0,19710,864000
1290727,72271,99243,mymatlabjob,1,1,2023-05-31T23:51:20,2023-05-31T23:51:20,233,COMPLETED,0:0,...,0,1,0,0,0,0,1,0,66,86400
1290728,72271,99243,mymatlabjob,1,1,2023-05-31T23:54:14,2023-05-31T23:54:14,233,COMPLETED,0:0,...,0,1,0,0,0,0,1,0,18114,86400

In [65]:
#Target Encoding

encoder = ce.TargetEncoder()
target_encoding_1_data = encoder.fit_transform(data['JobName'], data['Elapsed_Seconds'])
#добавление новой колонки
data = pd.concat([data, target_encoding_1_data], axis=1)
data = data.drop(columns=['JobName'])

display(data)

,UID,GID,ReqNodes,ReqCPUS,Submit,Start,Priority,State,ExitCode,astrophys,...,mech,phys,radiophys,cascade,g2,nv,tornado,tornado-k40,Elapsed_Seconds,Timelimit_Seconds
0,1420,88068,70,1960,2021-08-11T16:53:04,2021-09-17T09:46:21,1,CANCELLED by 50260,0:0,1,...,0,0,0,0,0,0,1,0,127649,864000
1,52951,3414,2,56,2021-08-18T10:38:10,2021-08-18T10:46:12,1,TIMEOUT,0:0,0,...,0,1,0,0,0,0,1,0,1209638,1209600
2,24801,97723,6,168,2021-08-18T14:50:05,2021-08-18T14:50:05,1,CANCELLED by 50341,0:0,0,...,1,0,0,0,0,0,1,0,1199140,1209600
3,24801,97723,6,168,2021-08-18T14:52:31,2021-08-18T14:52:32,1,CANCELLED by 50341,0:0,0,...,1,0,0,0,0,0,1,0,1199079,1209600
4,70802,33028,1,1,2021-08-19T15:33:49,2021-08-19T15:33:50,1,TIMEOUT,0:0,0,...,0,0,0,0,0,0,0,1,1209604,1209600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1290724,70637,47128,1,28,2023-05-31T23:42:30,2023-05-31T23:42:30,480,COMPLETED,0:0,0,...,1,0,0,0,0,0,1,0,19177,864000
1290725,70637,47128,1,28,2023-05-31T23:42:47,2023-05-31T23:42:47,480,COMPLETED,0:0,0,...,1,0,0,0,0,0,1,0,19522,864000
1290726,70637,47128,1,28,2023-05-31T23:43:10,2023-05-31T23:43:12,480,COMPLETED,0:0,0,...,1,0,0,0,0,0,1,0,19710,864000
1290727,72271,99243,1,1,2023-05-31T23:51:20,2023-05-31T23:51:20,233,COMPLETED,0:0,0,...,0,1,0,0,0,0,1,0,66,86400
1290728,72271,99243,1,1,2023-05-31T23:54:14,2023-05-31T23:54:14,233,COMPLETED,0:0,0,...,0,1,0,0,0,0,1,0,18114,86400

In [66]:
data['Submit'] = pd.to_datetime(data['Submit'])
data['Start'] = pd.to_datetime(data['Start'])

#Создание нового признака
data['TimeWeit'] = data['Start'] - data['Submit']
data = data.drop(columns=['Start'])
data = data.drop(columns=['Submit'])

display(data)

,UID,GID,ReqNodes,ReqCPUS,Priority,State,ExitCode,astrophys,bioinf,biophys,...,phys,radiophys,cascade,g2,nv,tornado,tornado-k40,Elapsed_Seconds,Timelimit_Seconds,TimeWeit
0,1420,88068,70,1960,1,CANCELLED by 50260,0:0,1,0,0,...,0,0,0,0,0,1,0,127649,864000,36 days 16:53:17
1,52951,3414,2,56,1,TIMEOUT,0:0,0,0,0,...,1,0,0,0,0,1,0,1209638,1209600,0 days 00:08:02
2,24801,97723,6,168,1,CANCELLED by 50341,0:0,0,0,0,...,0,0,0,0,0,1,0,1199140,1209600,0 days 00:00:00
3,24801,97723,6,168,1,CANCELLED by 50341,0:0,0,0,0,...,0,0,0,0,0,1,0,1199079,1209600,0 days 00:00:01
4,70802,33028,1,1,1,TIMEOUT,0:0,0,0,0,...,0,0,0,0,0,0,1,1209604,1209600,0 days 00:00:01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1290724,70637,47128,1,28,480,COMPLETED,0:0,0,0,0,...,0,0,0,0,0,1,0,19177,864000,0 days 00:00:00
1290725,70637,47128,1,28,480,COMPLETED,0:0,0,0,0,...,0,0,0,0,0,1,0,19522,864000,0 days 00:00:00
1290726,70637,47128,1,28,480,COMPLETED,0:0,0,0,0,...,0,0,0,0,0,1,0,19710,864000,0 days 00:00:02
1290727,72271,99243,1,1,233,COMPLETED,0:0,0,0,0,...,1,0,0,0,0,1,0,66,86400,0 days 00:00:00
1290728,72271,99243,1,1,233,COMPLETED,0:0,0,0,0,...,1,0,0,0,0,1,0,18114,86400,0 days 00:00:00

In [ ]:
print(data['TimeWeit'])

In [67]:
#Преобразование данных TimeWeit
def parse_time_new(time_str):
    #разделение строки времени на дни и время
    days, time = str(time_str).split(' days ')
    hours, minutes, seconds = map(int, time.split(':'))
    result = int(days)*86400 + hours*3600 + minutes*60 + seconds
    return result

# Применение функции к каждой строке столбца
data['TimeWeit_Seconds'] = data['TimeWeit'].apply(parse_time_new)
data = data.drop(columns=['TimeWeit'])

In [68]:
#Удаляем ExitCode, потому что State содержит об этом информацию
data = data.drop(columns=['ExitCode'])

#Удаляем все неудачно завершенные задачи
data = data.loc[data['State'] == 'COMPLETED']
data = data.drop(columns=['State'])

display(data)

,UID,GID,ReqNodes,ReqCPUS,Priority,astrophys,bioinf,biophys,energ,geophys,...,phys,radiophys,cascade,g2,nv,tornado,tornado-k40,Elapsed_Seconds,Timelimit_Seconds,TimeWeit_Seconds
8,7072,62503,1,1,1,0,0,0,0,0,...,0,0,0,0,0,1,0,959072,1036800,7830
9,7072,62503,1,1,1,0,0,0,0,0,...,0,0,0,0,0,1,0,959042,1209600,7858
10,6799,22748,1,1,1,0,0,0,0,0,...,0,0,0,0,0,1,0,1045167,1209600,1
11,86601,79320,1,1,1,0,0,0,0,0,...,0,1,0,0,0,1,0,15099,28800,726879
12,86601,79320,1,1,1,0,0,0,0,0,...,0,1,0,0,0,1,0,15326,28800,726920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1290724,70637,47128,1,28,480,0,0,0,0,0,...,0,0,0,0,0,1,0,19177,864000,0
1290725,70637,47128,1,28,480,0,0,0,0,0,...,0,0,0,0,0,1,0,19522,864000,0
1290726,70637,47128,1,28,480,0,0,0,0,0,...,0,0,0,0,0,1,0,19710,864000,2
1290727,72271,99243,1,1,233,0,0,0,0,0,...,1,0,0,0,0,1,0,66,86400,0
1290728,72271,99243,1,1,233,0,0,0,0,0,...,1,0,0,0,0,1,0,18114,86400,0

###Обучение lgb c категориями

In [12]:
!pip install lightgbm

Requirement already satisfied: lightgbm in /usr/local/lib/python3.10/dist-packages (4.1.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from lightgbm) (1.25.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from lightgbm) (1.11.4)

In [13]:
import lightgbm as lgb
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [52]:
X = data.drop('Elapsed_Seconds', axis=1)
Y = data.iloc[:, 20]

In [ ]:
data.iloc[:, 20]

In [23]:
#Разделение на тестовую и обучающие выборки
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [24]:
#Обучение модели LightGBM
train_data = lgb.Dataset(X_train, label=Y_train)
test_data = lgb.Dataset(X_test, label=Y_test)

param = {'objective': 'regression', 'metric': 'mse'}
num_round = 500
lgb_model = lgb.train(param, train_data, num_round, valid_sets=[test_data])

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.018597 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 877
[LightGBM] [Info] Number of data points in the train set: 231270, number of used features: 21
[LightGBM] [Info] Start training from score 9159.303338

In [25]:
#Предсказание и оценка модели на тестовой выборке
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

Y_pred = lgb_model.predict(X_test)

mse = mean_squared_error(Y_test, Y_pred)
print("Mean Squared Error:", mse)

r2 = r2_score(Y_test, Y_pred)
print("R2 score:", r2)

Mean Squared Error: 967258836.0352232
R2 score: 0.5281338286955516

In [ ]:
#Предсказание и оценка модели на обучающей выборке

Y_train_pred = lgb_model.predict(X_train)

mse = mean_squared_error(Y_train, Y_train_pred)
print("Mean Squared Error:", mse)

r2 = r2_score(Y_train, Y_train_pred)
print("R2 score:", r2)

Mean Squared Error: 698983514.0196756
R2 score: 0.6558146343920568

## Обучение без категорий

In [4]:
data = df1
#удаление колонки с индексами строк
first_column_name = data.columns[0]
data = data.drop(columns=[first_column_name])
display(data)

,UID,GID,JobName,Partition,ReqNodes,ReqCPUS,Timelimit,Submit,Start,Elapsed,Priority,State,ExitCode
0,1420,88068,Smilei0,tornado,70,1960,10-00:00:00,2021-08-11T16:53:04,2021-09-17T09:46:21,1-11:27:29,1,CANCELLED by 50260,0:0
1,52951,3414,v149_td,tornado,2,56,14-00:00:00,2021-08-18T10:38:10,2021-08-18T10:46:12,14-00:00:38,1,TIMEOUT,0:0
2,24801,97723,fluent,tornado,6,168,14-00:00:00,2021-08-18T14:50:05,2021-08-18T14:50:05,13-21:05:40,1,CANCELLED by 50341,0:0
3,24801,97723,fluent,tornado,6,168,14-00:00:00,2021-08-18T14:52:31,2021-08-18T14:52:32,13-21:04:39,1,CANCELLED by 50341,0:0
4,70802,33028,dcss.slurm,tornado-k40,1,1,14-00:00:00,2021-08-19T15:33:49,2021-08-19T15:33:50,14-00:00:04,1,TIMEOUT,0:0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1301870,70637,47128,lsdyna,tornado,1,28,10-00:00:00,2023-05-31T23:42:30,2023-05-31T23:42:30,05:19:37,480,COMPLETED,0:0
1301871,70637,47128,lsdyna,tornado,1,28,10-00:00:00,2023-05-31T23:42:47,2023-05-31T23:42:47,05:25:22,480,COMPLETED,0:0
1301872,70637,47128,lsdyna,tornado,1,28,10-00:00:00,2023-05-31T23:43:10,2023-05-31T23:43:12,05:28:30,480,COMPLETED,0:0
1301873,72271,99243,mymatlabjob,tornado,1,1,1-00:00:00,2023-05-31T23:51:20,2023-05-31T23:51:20,00:01:06,233,COMPLETED,0:0
1301874,72271,99243,mymatlabjob,tornado,1,1,1-00:00:00,2023-05-31T23:54:14,2023-05-31T23:54:14,05:01:54,233,COMPLETED,0:0

In [5]:
#Преобразование категориального признака

#One-Hot Encoding
#признак "Partition"
one_hot_encoding_2_data = pd.get_dummies(data['Partition'])
#добавление новых колонок к исходному датафрейму
data = pd.concat([data, one_hot_encoding_2_data], axis=1)
data = data.drop(columns=['Partition'])

In [6]:
!pip install category_encoders
import category_encoders as ce

Collecting category_encoders
  Downloading category_encoders-2.6.3-py2.py3-none-any.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.9/81.9 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.25.2)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.11.4)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.14.1)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.5.3)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.5.6)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2023.4)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.3.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (23.2)
Installing collected packages: category_encoders
Successfully installed category_encoders-2.6.3

In [7]:
#Преобразование форматов столцов Elapsed_Seconds и Timelimit
def parse_time(time_str):
    if '-' in time_str:
        days, time = time_str.split('-')
    else:
        days = '0'
        time = time_str
    hours, minutes, seconds = map(int, time.split(':'))
    result = int(days)*86400 + hours*3600 + minutes*60 + seconds
    return result

# Применение функции к каждой строке столбца
data['Elapsed_Seconds'] = data['Elapsed'].apply(parse_time)
data = data.drop(columns=['Elapsed'])

data['Timelimit_Seconds'] = data['Timelimit'].apply(parse_time)
data = data.drop(columns=['Timelimit'])

In [8]:
#Target Encoding
encoder = ce.TargetEncoder()
target_encoding_1_data = encoder.fit_transform(data['JobName'], data['Elapsed_Seconds'])
#добавление новой колонки
data = pd.concat([data, target_encoding_1_data], axis=1)
data = data.drop(columns=['JobName'])

In [9]:
data['Submit'] = pd.to_datetime(data['Submit'])
data['Start'] = pd.to_datetime(data['Start'])

#Создание нового признака
data['TimeWeit'] = data['Start'] - data['Submit']
data = data.drop(columns=['Start'])
data = data.drop(columns=['Submit'])

#Преобразование данных TimeWeit
def parse_time_new(time_str):
    #разделение строки времени на дни и время
    days, time = str(time_str).split(' days ')
    hours, minutes, seconds = map(int, time.split(':'))
    result = int(days)*86400 + hours*3600 + minutes*60 + seconds
    return result

# Применение функции к каждой строке столбца
data['TimeWeit_Seconds'] = data['TimeWeit'].apply(parse_time_new)
data = data.drop(columns=['TimeWeit'])

In [10]:
#Удаляем ExitCode, потому что State содержит об этом информацию
data = data.drop(columns=['ExitCode'])

#Удаляем все неудачно завершенные задачи
data = data.loc[data['State'] == 'COMPLETED']
data = data.drop(columns=['State'])

display(data)

,UID,GID,ReqNodes,ReqCPUS,Priority,cascade,g2,nv,tornado,tornado-k40,Elapsed_Seconds,Timelimit_Seconds,TimeWeit_Seconds
8,7072,62503,1,1,1,0,0,0,1,0,959072,1036800,7830
9,7072,62503,1,1,1,0,0,0,1,0,959042,1209600,7858
10,6799,22748,1,1,1,0,0,0,1,0,1045167,1209600,1
11,86601,79320,1,1,1,0,0,0,1,0,15099,28800,726879
12,86601,79320,1,1,1,0,0,0,1,0,15326,28800,726920
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1301870,70637,47128,1,28,480,0,0,0,1,0,19177,864000,0
1301871,70637,47128,1,28,480,0,0,0,1,0,19522,864000,0
1301872,70637,47128,1,28,480,0,0,0,1,0,19710,864000,2
1301873,72271,99243,1,1,233,0,0,0,1,0,66,86400,0
1301874,72271,99243,1,1,233,0,0,0,1,0,18114,86400,0

In [11]:
!pip install lightgbm

Requirement already satisfied: lightgbm in /usr/local/lib/python3.10/dist-packages (4.1.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from lightgbm) (1.25.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from lightgbm) (1.11.4)

In [12]:
import lightgbm as lgb
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [13]:
X = data.drop('Elapsed_Seconds', axis=1)
Y = data.iloc[:, 10]

In [20]:
#Разделение на тестовую и обучающие выборки
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [122]:
#Обучение модели LightGBM
train_data = lgb.Dataset(X_train, label=Y_train)
test_data = lgb.Dataset(X_test, label=Y_test)

param = {'objective': 'regression', 'metric': 'mse'}
num_round = 3000
lgb_model = lgb.train(param, train_data, num_round, valid_sets=[test_data])

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.016238 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 821
[LightGBM] [Info] Number of data points in the train set: 241875, number of used features: 20
[LightGBM] [Info] Start training from score 9098.460035

In [123]:
#Предсказание и оценка модели на тестовой выборке
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

Y_pred = lgb_model.predict(X_test)

mse = mean_squared_error(Y_test, Y_pred)
print("Mean Squared Error:", mse)

r2 = r2_score(Y_test, Y_pred)
print("R2 score:", r2)

Mean Squared Error: 9745694583.303503
R2 score: -1.0832782956145404

In [ ]:
#Предсказание и оценка модели на обучающей выборке

Y_train_pred = lgb_model.predict(X_train)

mse = mean_squared_error(Y_train, Y_train_pred)
print("Mean Squared Error:", mse)

r2 = r2_score(Y_train, Y_train_pred)
print("R2 score:", r2)

Mean Squared Error: 367078594.2546677
R2 score: 0.7457012938655686

##Применение Байесовской оптимизации для подбора гиперпараметров и обучение после

In [98]:
!pip install scikit-optimize

Requirement already satisfied: scikit-optimize in /usr/local/lib/python3.10/dist-packages (0.10.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.3.2)
Requirement already satisfied: pyaml>=16.9 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (23.12.0)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.25.2)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.11.4)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.2.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (24.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from pyaml>=16.9->scikit-optimize) (6.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.0.0->scikit-optimize) (3.3.0)

In [99]:
from skopt import BayesSearchCV
from lightgbm import LGBMRegressor
from sklearn.model_selection import train_test_split

In [ ]:
# Загрузка данных
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Определение модели LightGBM
model = LGBMRegressor()

# Определение пространства поиска гиперпараметров
param_space = {
    'learning_rate': (0.01, 1.0, 'log-uniform'),
    'n_estimators': (50, 1000),
    'max_depth': (1, 20),
    'num_leaves': (2, 50),
    'min_child_samples': (1, 20),
    'subsample': (0.1, 1.0, 'uniform'),
    'colsample_bytree': (0.1, 1.0, 'uniform')
}

# Создание объекта BayesSearchCV для байесовской оптимизации
opt = BayesSearchCV(model, param_space, n_iter=50, cv=3, scoring='neg_mean_squared_error', random_state=42)

# Поиск оптимальных гиперпараметров
opt.fit(X_train, Y_train)

# Вывод наилучших гиперпараметров
print("Best hyperparameters:", opt.best_params_)

# Оценка качества модели на тестовой выборке
mse = opt.score(X_test, Y_test)
print("Mean squared error on test data:", -mse)

Получилось, что
**Best hyperparameters:** OrderedDict([('colsample_bytree', 0.7782267583243515), ('learning_rate', 0.07721927983759985), ('max_depth', 14), ('min_child_samples', 6), ('n_estimators', 958), ('num_leaves', 40), ('subsample', 0.21384009862178982)])
Mean squared error on test data: 556241645.0411495

In [19]:
#Обучение модели на оптимальных параметрах
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Оптимальные гиперпараметры, полученные из байесовской оптимизации
optimal_params = {
    'learning_rate': 0.077219279837599855,
    'n_estimators': 958,
    'max_depth': 14,
    'num_leaves': 40,
    'min_child_samples': 6,
    'subsample': 0.21384009862178982,
    'colsample_bytree': 0.7782267583243515,
    'objective': 'regression',
    'metric': 'mse'
}

# Создание и обучение модели с оптимальными гиперпараметрами
model = LGBMRegressor(**optimal_params)
model.fit(X_train, Y_train)

# Оценка качества модели на тестовой выборке
r2 = model.score(X_test, Y_test)
print("R2 score:", r2)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.304123 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 997
[LightGBM] [Info] Number of data points in the train set: 999930, number of used features: 12
[LightGBM] [Info] Start training from score 6444.680011
R2 score: 0.6246588530760213

###Иной способ разделения на тестовую и обучающую выборку

In [55]:
# Найти строки, в которых uid встречается единожды
unique_uids = data['UID'].value_counts()
unique_uids = unique_uids[unique_uids == 1].index.tolist()

# Выбрать только те строки из данных, где значение uid встречается только один раз
test_data = data[data['UID'].isin(unique_uids)]

# Вычислить количество строк для test_data, чтобы оно составляло 20% от всего набора данных df
test_size = int(len(data) * 0.1)

# Взять test_size строк из test_data
test_data = test_data.head(test_size)

# Получить индексы строк, которые не вошли в test_data
remaining_indices = data.index.difference(test_data.index)

# Оставить только строки, которые не входят в test_data, в исходном наборе
train_data = data.loc[remaining_indices]

ValueError: Cannot take a larger sample than population when 'replace=False'

In [56]:
display(test_data)

,UID,GID,ReqNodes,ReqCPUS,Priority,astrophys,bioinf,biophys,energ,geophys,...,phys,radiophys,cascade,g2,nv,tornado,tornado-k40,Elapsed_Seconds,Timelimit_Seconds,TimeWeit_Seconds
4992,46222,7843,4.0,112.0,1.0,0,0,0,0,0,...,0,0,0,0,0,1,0,29568,864000,1
36059,39838,45050,4.0,16.0,1.0,0,0,0,0,0,...,0,0,0,0,0,1,0,8,900,0
47578,84777,72919,1.0,1.0,1.0,0,0,0,1,0,...,0,0,0,0,0,1,0,152,86400,6
51686,70653,67678,1.0,1.0,1.0,0,0,0,0,1,...,0,0,0,0,0,1,0,10,43200,1
157011,1790,95966,1.0,1.0,927.0,0,0,0,0,0,...,0,0,0,0,0,1,0,895,43200,1
169491,95377,99243,1.0,1.0,438.0,0,0,0,0,0,...,1,0,0,0,0,1,0,4,1209600,34629
282314,16165,22005,1.0,1.0,675.0,0,0,0,1,0,...,0,0,0,0,0,1,0,3589,432000,1
295507,47715,97152,1.0,1.0,2000.0,0,0,0,0,0,...,0,0,0,0,0,1,0,266,43200,1

In [42]:
X_train = train_data.drop('Elapsed_Seconds', axis=1)
X_test = test_data.drop('Elapsed_Seconds', axis=1)
Y_train = train_data.iloc[:, 10]
Y_test = test_data.iloc[:, 10]

display(X_train)
display(X_test)
display(Y_train)
display(Y_test)

,UID,GID,ReqNodes,ReqCPUS,Priority,astrophys,bioinf,biophys,energ,geophys,...,mech,phys,radiophys,cascade,g2,nv,tornado,tornado-k40,Timelimit_Seconds,TimeWeit_Seconds
8,7072,62503,1.0,1.0,1.0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1036800,7830
9,7072,62503,1.0,1.0,1.0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1209600,7858
10,6799,22748,1.0,1.0,1.0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,1209600,1
11,86601,79320,1.0,1.0,1.0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,28800,726879
12,86601,79320,1.0,1.0,1.0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,28800,726920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303742,50848,81833,1.0,16.0,2831.0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,172800,33585
303743,50848,81833,1.0,1.0,2831.0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,172800,12
303744,50848,81833,1.0,1.0,2831.0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,172800,11
303745,50848,81833,1.0,1.0,2831.0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,172800,6085
303746,50848,81833,1.0,1.0,2831.0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,172800,1

,UID,GID,ReqNodes,ReqCPUS,Priority,astrophys,bioinf,biophys,energ,geophys,...,mech,phys,radiophys,cascade,g2,nv,tornado,tornado-k40,Timelimit_Seconds,TimeWeit_Seconds
157011,1790,95966,1.0,1.0,927.0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,43200,1
282314,16165,22005,1.0,1.0,675.0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,432000,1
36059,39838,45050,4.0,16.0,1.0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,900,0
4992,46222,7843,4.0,112.0,1.0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,864000,1
295507,47715,97152,1.0,1.0,2000.0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,43200,1
51686,70653,67678,1.0,1.0,1.0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,43200,1
47578,84777,72919,1.0,1.0,1.0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,86400,6
169491,95377,99243,1.0,1.0,438.0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,1209600,34629

8         0
9         0
10        0
11        0
12        0
         ..
303742    0
303743    0
303744    0
303745    0
303746    0
Name: it, Length: 289080, dtype: uint8

157011    1
282314    0
36059     0
4992      0
295507    0
51686     0
47578     0
169491    0
Name: it, dtype: uint8

In [116]:
# Оптимальные гиперпараметры, полученные из байесовской оптимизации
optimal_params = {
    'learning_rate': 0.077219279837599855,
    'n_estimators': 958,
    'max_depth': 14,
    'num_leaves': 40,
    'min_child_samples': 6,
    'subsample': 0.21384009862178982,
    'colsample_bytree': 0.7782267583243515,
    'objective': 'regression',
    'metric': 'mse'
}

# Создание и обучение модели с оптимальными гиперпараметрами
model = LGBMRegressor(**optimal_params)
model.fit(X_train, Y_train)

Y_pred = model.predict(X_test)

# Оценка качества модели на тестовой выборке
r2 = model.score(X_test, Y_test)
mse = mean_squared_error(Y_test, Y_pred)
print("R2 score for test:", r2)
print("mse for test:", mse)

r2 = model.score(X_train, Y_train)
print("R2 score for train:", r2)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.020414 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 865
[LightGBM] [Info] Number of data points in the train set: 255336, number of used features: 22
[LightGBM] [Info] Start training from score 9302.048834
R2 score for test: -8.79403956061812
mse for test: 15784143093.315496
R2 score for train: 0.7332035363371429

##Добавляем окна

In [69]:
!pip install lightgbm
!pip install scikit-optimize

Requirement already satisfied: lightgbm in /usr/local/lib/python3.10/dist-packages (4.1.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from lightgbm) (1.25.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from lightgbm) (1.11.4)
Requirement already satisfied: scikit-optimize in /usr/local/lib/python3.10/dist-packages (0.10.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.3.2)
Requirement already satisfied: pyaml>=16.9 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (23.12.0)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.25.2)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.11.4)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.2.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (24.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from pyaml>=16.9->scikit-optimize) (6.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.0.0->scikit-optimize) (3.3.0)

In [70]:
import lightgbm as lgb
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [15]:
from skopt import BayesSearchCV
from lightgbm import LGBMRegressor
from sklearn.model_selection import train_test_split

In [42]:
len(data)

289088

In [71]:
display(data)

,UID,GID,ReqNodes,ReqCPUS,Priority,astrophys,bioinf,biophys,energ,geophys,...,phys,radiophys,cascade,g2,nv,tornado,tornado-k40,Elapsed_Seconds,Timelimit_Seconds,TimeWeit_Seconds
8,7072,62503,1,1,1,0,0,0,0,0,...,0,0,0,0,0,1,0,959072,1036800,7830
9,7072,62503,1,1,1,0,0,0,0,0,...,0,0,0,0,0,1,0,959042,1209600,7858
10,6799,22748,1,1,1,0,0,0,0,0,...,0,0,0,0,0,1,0,1045167,1209600,1
11,86601,79320,1,1,1,0,0,0,0,0,...,0,1,0,0,0,1,0,15099,28800,726879
12,86601,79320,1,1,1,0,0,0,0,0,...,0,1,0,0,0,1,0,15326,28800,726920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1290724,70637,47128,1,28,480,0,0,0,0,0,...,0,0,0,0,0,1,0,19177,864000,0
1290725,70637,47128,1,28,480,0,0,0,0,0,...,0,0,0,0,0,1,0,19522,864000,0
1290726,70637,47128,1,28,480,0,0,0,0,0,...,0,0,0,0,0,1,0,19710,864000,2
1290727,72271,99243,1,1,233,0,0,0,0,0,...,1,0,0,0,0,1,0,66,86400,0
1290728,72271,99243,1,1,233,0,0,0,0,0,...,1,0,0,0,0,1,0,18114,86400,0

In [72]:
#Сортировка по UID
data = data.sort_values(by='UID')
display(data)

,UID,GID,ReqNodes,ReqCPUS,Priority,astrophys,bioinf,biophys,energ,geophys,...,phys,radiophys,cascade,g2,nv,tornado,tornado-k40,Elapsed_Seconds,Timelimit_Seconds,TimeWeit_Seconds
761959,215,76557,1,1,3130,0,0,0,0,0,...,0,0,0,0,0,1,0,3722,86400,0
736450,215,76557,1,1,3653,0,0,0,0,0,...,0,0,0,0,0,1,0,91454,604800,1198
736451,215,76557,1,1,3653,0,0,0,0,0,...,0,0,0,0,0,1,0,92899,604800,1198
736452,215,76557,1,1,3596,0,0,0,0,0,...,0,0,0,0,0,1,0,78333,604800,1907
736453,215,76557,1,1,3596,0,0,0,0,0,...,0,0,0,0,0,1,0,92373,604800,1907
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215693,99914,53299,1,1,1054,0,0,0,0,0,...,0,0,0,0,0,1,0,86327,86400,1
1250623,99914,53299,1,1,831,0,0,0,0,0,...,0,0,0,0,0,1,0,2056,86400,8
1250075,99914,53299,1,1,828,0,0,0,0,0,...,0,0,0,0,0,1,0,1566,86400,3838
1255606,99914,53299,1,1,831,0,0,0,0,0,...,0,0,0,0,0,1,0,43757,86400,45033
1257038,99914,53299,1,1,681,0,0,0,0,0,...,0,0,0,0,0,1,0,46613,86400,1

In [73]:
#Создание столбца Mean_Elapsed_Seconds со средним значением Elapsed_Seconds по UID
data['Mean_Elapsed_Seconds'] = data.groupby('UID')['Elapsed_Seconds'].transform('mean')
display(data)

,UID,GID,ReqNodes,ReqCPUS,Priority,astrophys,bioinf,biophys,energ,geophys,...,radiophys,cascade,g2,nv,tornado,tornado-k40,Elapsed_Seconds,Timelimit_Seconds,TimeWeit_Seconds,Mean_Elapsed_Seconds
761959,215,76557,1,1,3130,0,0,0,0,0,...,0,0,0,0,1,0,3722,86400,0,72479.960526
736450,215,76557,1,1,3653,0,0,0,0,0,...,0,0,0,0,1,0,91454,604800,1198,72479.960526
736451,215,76557,1,1,3653,0,0,0,0,0,...,0,0,0,0,1,0,92899,604800,1198,72479.960526
736452,215,76557,1,1,3596,0,0,0,0,0,...,0,0,0,0,1,0,78333,604800,1907,72479.960526
736453,215,76557,1,1,3596,0,0,0,0,0,...,0,0,0,0,1,0,92373,604800,1907,72479.960526
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215693,99914,53299,1,1,1054,0,0,0,0,0,...,0,0,0,0,1,0,86327,86400,1,36126.200000
1250623,99914,53299,1,1,831,0,0,0,0,0,...,0,0,0,0,1,0,2056,86400,8,36126.200000
1250075,99914,53299,1,1,828,0,0,0,0,0,...,0,0,0,0,1,0,1566,86400,3838,36126.200000
1255606,99914,53299,1,1,831,0,0,0,0,0,...,0,0,0,0,1,0,43757,86400,45033,36126.200000
1257038,99914,53299,1,1,681,0,0,0,0,0,...,0,0,0,0,1,0,46613,86400,1,36126.200000

In [20]:
# Создание столбца Mean_2_Elapsed_Seconds средних значений Mean_Elapsed_Seconds с окном 2
# Создаем DataFrame с значениями столбца Elapsed_Seconds
elapsed_seconds_df = data[['UID', 'Elapsed_Seconds']]

# Рассчитываем скользящее среднее
rolling_mean = data.groupby('UID')['Elapsed_Seconds'].rolling(window=2).mean()
# Преобразуем rolling_mean в DataFrame и сбрасываем мультииндекс
rolling_mean_df = rolling_mean.reset_index(level=0, drop=True)

# Объединяем значения Elapsed_Seconds и скользящие средние в новый DataFrame
result_df = pd.concat([elapsed_seconds_df, rolling_mean_df], axis=1)
result_df.columns = ['UID', 'Elapsed_Seconds', 'Rolling_Mean']

# Фильтруем DataFrame для выбранного UID (например, UID=458)
uid_filtered_df = result_df[result_df['UID'] == 458]

# Устанавливаем максимальное количество строк для вывода без сокращения
#pd.set_option('display.max_rows', None)

# Выводим DataFrame
print(uid_filtered_df)

        UID  Elapsed_Seconds  Rolling_Mean
273781  458              152           NaN
282575  458             5229        2690.5
180083  458                3        2616.0
180082  458            12628        6315.5
178090  458                5        6316.5
...     ...              ...           ...
273793  458              145         146.0
273791  458              146         145.5
273789  458              146         146.0
274319  458              147         146.5
170424  458              176         161.5

[85 rows x 3 columns]

In [21]:
pd.set_option('display.max_rows', 10)
# Добавляем скользящее среднее в исходный DataFrame
data['Mean_2_Elapsed_Seconds'] = rolling_mean_df
# Выводим обновленный DataFrame
display(data)

,UID,GID,ReqNodes,ReqCPUS,Priority,astrophys,bioinf,biophys,energ,geophys,...,cascade,g2,nv,tornado,tornado-k40,Elapsed_Seconds,Timelimit_Seconds,TimeWeit_Seconds,Mean_Elapsed_Seconds,Mean_2_Elapsed_Seconds
273781,458,94913,1.0,1.0,3138.0,0,0,0,0,1,...,0,0,0,1,0,152,518400,0,1015.941176,NaN
282575,458,94913,1.0,1.0,3020.0,0,0,0,0,1,...,0,0,0,1,0,5229,518400,0,1015.941176,2690.5
180083,458,94913,1.0,1.0,4502.0,0,0,0,0,1,...,0,0,0,1,0,3,518400,0,1015.941176,2616.0
180082,458,94913,1.0,1.0,4502.0,0,0,0,0,1,...,0,0,0,1,0,12628,518400,0,1015.941176,6315.5
178090,458,94913,1.0,1.0,4509.0,0,0,0,0,1,...,0,0,0,1,0,5,518400,1,1015.941176,6316.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35892,99676,67844,8.0,8.0,1.0,0,0,0,0,0,...,0,0,0,1,0,2707,172800,1,3713.234043,2799.0
24017,99676,67844,2.0,2.0,1.0,0,0,0,0,0,...,0,0,0,1,0,2891,172800,381,3713.234043,2799.0
24015,99676,67844,2.0,2.0,1.0,0,0,0,0,0,...,0,0,0,1,0,2881,172800,363,3713.234043,2886.0
28234,99676,67844,3.0,3.0,1.0,0,0,0,0,0,...,0,0,0,1,0,2696,172800,1,3713.234043,2788.5
35895,99676,67844,8.0,8.0,1.0,0,0,0,0,0,...,0,0,0,1,0,2825,172800,0,3713.234043,2760.5

In [74]:
# Создание столбцов с различными размерами окон средних
# Создаем DataFrame со значениями столбца Elapsed_Seconds
elapsed_seconds_df = data[['UID', 'Elapsed_Seconds']]

# Размеры окон для скользящих средних
window_sizes = [2, 4, 8, 16, 32, 64]

for window_size in window_sizes:
    # Рассчитываем скользящее среднее
    rolling_mean = data.groupby('UID')['Elapsed_Seconds'].rolling(window=window_size, min_periods=1).mean()
    # Преобразуем rolling_mean в DataFrame
    rolling_mean_df = rolling_mean.reset_index(level=0, drop=True)
    # Добавляем столбец со скользящим средним в исходный DataFrame
    data[f'Mean_{window_size}_Elapsed_Seconds'] = rolling_mean_df

# Выводим обновленный DataFrame
display(data)

,UID,GID,ReqNodes,ReqCPUS,Priority,astrophys,bioinf,biophys,energ,geophys,...,Elapsed_Seconds,Timelimit_Seconds,TimeWeit_Seconds,Mean_Elapsed_Seconds,Mean_2_Elapsed_Seconds,Mean_4_Elapsed_Seconds,Mean_8_Elapsed_Seconds,Mean_16_Elapsed_Seconds,Mean_32_Elapsed_Seconds,Mean_64_Elapsed_Seconds
761959,215,76557,1,1,3130,0,0,0,0,0,...,3722,86400,0,72479.960526,3722.0,3722.000000,3722.000000,3722.000000,3722.000000,3722.000000
736450,215,76557,1,1,3653,0,0,0,0,0,...,91454,604800,1198,72479.960526,47588.0,47588.000000,47588.000000,47588.000000,47588.000000,47588.000000
736451,215,76557,1,1,3653,0,0,0,0,0,...,92899,604800,1198,72479.960526,92176.5,62691.666667,62691.666667,62691.666667,62691.666667,62691.666667
736452,215,76557,1,1,3596,0,0,0,0,0,...,78333,604800,1907,72479.960526,85616.0,66602.000000,66602.000000,66602.000000,66602.000000,66602.000000
736453,215,76557,1,1,3596,0,0,0,0,0,...,92373,604800,1907,72479.960526,85353.0,88764.750000,71756.200000,71756.200000,71756.200000,71756.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215693,99914,53299,1,1,1054,0,0,0,0,0,...,86327,86400,1,36126.200000,54280.0,43928.000000,44545.000000,44545.000000,44545.000000,44545.000000
1250623,99914,53299,1,1,831,0,0,0,0,0,...,2056,86400,8,36126.200000,44191.5,38532.250000,38475.142857,38475.142857,38475.142857,38475.142857
1250075,99914,53299,1,1,828,0,0,0,0,0,...,1566,86400,3838,36126.200000,1811.0,28045.500000,33861.500000,33861.500000,33861.500000,33861.500000
1255606,99914,53299,1,1,831,0,0,0,0,0,...,43757,86400,45033,36126.200000,22661.5,33426.500000,33699.875000,34961.000000,34961.000000,34961.000000
1257038,99914,53299,1,1,681,0,0,0,0,0,...,46613,86400,1,36126.200000,45185.0,23498.000000,33713.000000,36126.200000,36126.200000,36126.200000

In [102]:
# Разделение на тестовую и обучающую выборки
# Вычислить количество строк для test_data, чтобы оно составляло 20% от всего набора данных df
test_size = int(len(data) * 0.15)
test_data = pd.DataFrame()
train_data = data

while len(test_data) < test_size:
    # Выберите случайное значение из столбца 'UID'
    random_uid = train_data['UID'].sample().iloc[0]
    num_rows_with_uid = len(data[data['UID'] == random_uid])

    # Если количество строк не превышает test_size, добавляем в тест
    if num_rows_with_uid <= 0.3*test_size:
        test_data = test_data.append(train_data[train_data['UID'] == random_uid])
        # Удалите выбранные строки из исходного датафрейма
        train_data = train_data.drop(train_data[train_data['UID'] == random_uid].index)
    else:
        random_uid = train_data['UID'].sample().iloc[0]
        num_rows_with_uid = len(train_data[train_data['UID'] == random_uid])
        continue


Y_train = train_data.iloc[:, 20]
Y_test = test_data.iloc[:, 20]
X_train = train_data.drop('Elapsed_Seconds', axis=1)
X_test = test_data.drop('Elapsed_Seconds', axis=1)

<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])
<ipython-input-102-0e8e62b39c81>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = test_data.append(train_data[train_data['UID'] == random_uid])

In [92]:
#Обучение модели LightGBM
train_data = lgb.Dataset(X_train, label=Y_train)
test_data = lgb.Dataset(X_test, label=Y_test)

param = {'objective': 'regression', 'metric': 'mse'}
num_round = 5000
lgb_model = lgb.train(param, train_data, num_round, valid_sets=[test_data])

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.247071 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2652
[LightGBM] [Info] Number of data points in the train set: 1028960, number of used features: 29
[LightGBM] [Info] Start training from score 5590.572097

In [94]:
#Предсказание и оценка модели на тестовой выборке
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

Y_pred = lgb_model.predict(X_test)

mse = mean_squared_error(Y_test, Y_pred)
print("Mean Squared Error:", mse)

r2 = r2_score(Y_test, Y_pred)
print("R2 score:", r2)

Mean Squared Error: 884520418.2130965
R2 score: 0.7281491139401758

In [95]:
#Упаковка модели lgb в файл
import pickle
model = lgb_model
with open('model_1.pkl', 'wb') as f:
    pickle.dump(model, f)

In [96]:
#Загрузка модели из файла
model_path = 'model_1.pkl'
with open(model_path, 'rb') as f:
    model_1 = pickle.load(f)
Y_pred = model_1.predict(X_test)

r2 = r2_score(Y_test, Y_pred)
print("R2 score:", r2)

R2 score: 0.7281491139401758

In [ ]:
#Подбор гиперпараметров
# Определение пространства поиска гиперпараметров
param_space = {
    'learning_rate': (0.01, 1.0, 'log-uniform'),
    'n_estimators': (50, 1000),
    'max_depth': (1, 20),
    'num_leaves': (2, 50),
    'min_child_samples': (1, 20),
    'subsample': (0.1, 1.0, 'uniform'),
    'colsample_bytree': (0.1, 1.0, 'uniform')
}

# Создание объекта BayesSearchCV для байесовской оптимизации
opt = BayesSearchCV(model, param_space, n_iter=50, cv=3, scoring='neg_mean_squared_error', random_state=42)

# Поиск оптимальных гиперпараметров
opt.fit(X_train, Y_train)

# Вывод наилучших гиперпараметров
print("Best hyperparameters:", opt.best_params_)

# Оценка качества модели на тестовой выборке
mse = opt.score(X_test, Y_test)
print("Mean squared error on test data:", -mse)

Best hyperparameters: OrderedDict([('colsample_bytree', 0.13071357258784738), ('learning_rate', 0.01), ('max_depth', 19), ('min_child_samples', 4), ('n_estimators', 505), ('num_leaves', 40), ('subsample', 0.2691629153653792)])
Mean squared error on test data: 5056472204.663036

In [ ]:
# Оптимальные гиперпараметры, полученные из байесовской оптимизации
optimal_params = {
    'learning_rate': 0.01,
    'n_estimators': 505,
    'max_depth': 19,
    'num_leaves': 40,
    'min_child_samples': 4,
    'subsample': 0.2691629153653792,
    'colsample_bytree': 0.13071357258784738,
    'objective': 'regression',
    'metric': 'mse'
}

# Создание и обучение модели с оптимальными гиперпараметрами
model_LGB = LGBMRegressor(**optimal_params)
model_LGB.fit(X_train, Y_train)

Y_pred = model_LGB.predict(X_test)

# Оценка качества модели на тестовой выборке
r2 = model_LGB.score(X_test, Y_test)
mse = mean_squared_error(Y_test, Y_pred)
print("R2 score for test:", r2)
print("mse for test:", mse)

r2 = model_LGB.score(X_train, Y_train)
print("R2 score for train:", r2)

In [82]:
#Упаковка модели LGB в файл
import pickle
model = model_LGB
with open('model_2.pkl', 'wb') as f:
    pickle.dump(model, f)

In [83]:
#Загрузка модели из файла
model_path = 'model_2.pkl'
with open(model_path, 'rb') as f:
    model_2 = pickle.load(f)
Y_pred = model_2.predict(X_test)

r2 = r2_score(Y_test, Y_pred)
print("R2 score:", r2)

R2 score: 0.6632483541513997